import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import "@fontsource/nunito"
import { useUser } from '@/modules/hooks/useUser'
import { createServerSupabaseClient } from '@/modules/supabase'
import { NextRequest } from 'next/server'
import { GetServerSidePropsContext, NextPage } from 'next'


const inter = Inter({ subsets: ['latin'] })

const Home = (props:NextPage) => {
  console.log(props)
 
  return (
    <>
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by News App" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          Main Page
      </main>
    </>
  )
}


export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  console.log('test')
  const supabase = createServerSupabaseClient(ctx);
  const user = await supabase.auth.getSession()
  console.log(user)

  return {
    props:{}
  }
}

export default Home;