import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import "@fontsource/nunito"

import { GetServerSidePropsContext, NextPage } from 'next'


import NewsPage from '@/components/news'
import { QueryClient, dehydrate } from '@tanstack/react-query'
import { newsService } from '@/modules/services/news'
import SubNavLayout from '@/Project/layouts/subNavLayout'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

const Home = (props:NextPage) => {
  // //console.log(props)
 
  return (
    <>
      <Head>
        <title>News App</title>
        <meta name="description" content="Generated by News App" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
          <NewsPage />
      </main>
    </>
  )
}

// export async function getServerSideProps() {
//   const queryClient = new QueryClient()
//   await queryClient.prefetchQuery({
//     queryKey:['news'],
//     queryFn: newsService,
//   })

//   return {
//     props:{
//       dehydratedState: dehydrate(queryClient),
//     }
//   }

// }


Home.getLayout = function getLayout(page:ReactNode) {
  return (
    <SubNavLayout>
      {page}
    </SubNavLayout>
  )
}

// export const getServerSideProps = async (ctx:GetServerSidePropsContext) => {


//   // const supabase = createServerSupabaseClient(ctx);
//   // const {
//   //   data: { session }
//   // } = await supabase.auth.getSession();
//   // // //console.log(session)
//   // if (!session)
//   //   return {
//   //     redirect: {
//   //       destination: '/signin',
//   //       permanent: false
//   //     }
//   //   };



//   return {
//     props:{}
//   }
// }

export default Home;