import Head from 'next/head'
import Image from 'next/image'
// import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import "@fontsource/nunito"
import { Container } from '@mui/material'
import CardComp from '@/components/cards'
import SignIn from '@/components/auth/signIn'


// const inter = Inter({ subsets: ['latin'] })

export default function SingInPage() {
 

  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by News App" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Container 
            sx={{
                display:'flex',
                justifyContent:'center',
               
            }}
        >
            <CardComp 
                sx={{
                    
                }}
            >

                        <SignIn  /> 

               
            </CardComp>   
        </Container>
      </main>
    </>
  )
}
